#!/bin/sh
cp auto_backlight_bkg/bin/Debug/auto_backlight_bkg www/.
cp GdsScreenTest/bin/Debug/GdsScreenTest www/.
cp GdsScreenTest/bin/Debug/GdsScreenTestWrite www/.
cp GdsGamma/bin/Debug/GdsGamma www/.
cp NovaCSC/bin/Debug/NovaCSC www/.
cp GDSBT_iptcom/bin/Debug/GDSBT_iptcom www/.
cp GDSBT_iptcom/xml/TFT1.car1.lCst_20160812.xml www/.
cp GdsFlashImage/bin/Debug/GdsFlashImage www/.
cp POST_GreenSquare/bin/Debug/POST_GreenSquare www/.
cp www/AutoRun.sh FlasherScripts/AutoRun.sh_GDS
cp FlasherScripts/gds_flasher www/.

tar cf www.tar www

chmod 777 www.tar
