#ifndef MCG_EDS_ICD_H
#define MCG_EDS_ICD_H
/* 
     This file is autogenerated. 
     ICD_DB_VERSION 1.0.0.0
     DEVICE_INTERFACE_VERSION 1.0.4.0
     GDB_TOOL_VERSION 5.10.5

*/

 // ComID constants
#define COMID_OEDSREPPREPDATA_2 ((unsigned long int)847)
#define COMID_OEDSREPPREPDATA_3 ((unsigned long int)847)
#define COMID_IEDSREQPREPDATA3_3 ((unsigned long int)856)
#define COMID_IEDSREQPREPDATA3_5 ((unsigned long int)856)
#define COMID_OMCGDLFTFST ((unsigned long int)854)
#define COMID_IMCGREPFTFST ((unsigned long int)845)
#define COMID_IMCGREPREQ2SENDF ((unsigned long int)841)
#define COMID_OMCGREPREQFILE ((unsigned long int)843)
#define COMID_OMCGREPSENDFILE ((unsigned long int)851)
#define COMID_OMCGREQFTFST ((unsigned long int)844)
#define COMID_OMCGREQREQ2SENDF ((unsigned long int)840)
#define COMID_IMCGREQREQFILE ((unsigned long int)842)
#define COMID_IMCGREQSENDFILE ((unsigned long int)850)


const unsigned long int EDSREPPREPDATAMESSAGEHEADER_RESERVED1_SIZE = 4;
typedef struct {
	unsigned long int version;
	long int resultCode;
	unsigned long int timeMsgSent;
	unsigned long int timeMsgValidity;
	unsigned long int dataID;
	unsigned long int waysideRef;
	unsigned long int Reserved1[EDSREPPREPDATAMESSAGEHEADER_RESERVED1_SIZE];
} CEDSRepPrepDataMessageHeader;


typedef struct {
	unsigned long int appVersion;
	long int appResultCode;
} CEDSRepPrepDataMessageData;


typedef struct {
	CEDSRepPrepDataMessageHeader MessageHeader;
	CEDSRepPrepDataMessageData MessageData;
} CEDSRepPrepData;


const unsigned long int EDSREQPREPDATA3MESSAGEHEADER_RESERVED1_SIZE = 4;
typedef struct {
	unsigned long int version;
	long int resultCode;
	unsigned long int timeMsgSent;
	unsigned long int timeMsgValidity;
	unsigned long int dataID;
	unsigned long int waysideRef;
	unsigned long int Reserved1[EDSREQPREPDATA3MESSAGEHEADER_RESERVED1_SIZE];
} CEDSReqPrepData3MessageHeader;


const unsigned long int EDSREQPREPDATA3MESSAGEDATA_DATALOCATION_SIZE = 64;
const unsigned long int EDSREQPREPDATA3MESSAGEDATA_MCGFRAMEWORKURI_SIZE = 80;
const unsigned long int EDSREQPREPDATA3MESSAGEDATA_RESERVED1_SIZE = 4;
const unsigned long int EDSREQPREPDATA3MESSAGEDATA_SPECIFICPARAMETERS_SIZE = 1024;
typedef struct {
	unsigned long int appVersion;
	unsigned long int transactionID;
	unsigned char dataLocation[EDSREQPREPDATA3MESSAGEDATA_DATALOCATION_SIZE];
	unsigned char mcgFrameworkUri[EDSREQPREPDATA3MESSAGEDATA_MCGFRAMEWORKURI_SIZE];
	unsigned long int Reserved1[EDSREQPREPDATA3MESSAGEDATA_RESERVED1_SIZE];
	unsigned short int Reserved2;
	unsigned short int noOfChars;
	unsigned char specificParameters[EDSREQPREPDATA3MESSAGEDATA_SPECIFICPARAMETERS_SIZE];
} CEDSReqPrepData3MessageData;


typedef struct {
	CEDSReqPrepData3MessageHeader MessageHeader;
	CEDSReqPrepData3MessageData MessageData;
} CEDSReqPrepData3;


typedef struct {
	unsigned long int appVersion;
	long int appResultCode;
	unsigned long int transactionID;
} CMCGDLFTfSt;


typedef struct {
	unsigned long int appVersion;
	long int appResultCode;
} CMCGRepFTfSt;


typedef struct {
	unsigned long int appVersion;
	long int appResultCode;
	unsigned long int transactionID;
} CMCGRepReq2SendF;


typedef struct {
	unsigned long int appVersion;
	long int appResultCode;
} CMCGRepReqFile;


typedef struct {
	unsigned long int appVersion;
	long int appResultCode;
} CMCGRepSendFile;


typedef struct {
	unsigned long int appVersion;
	long int appResultCode;
	unsigned long int transactionID;
	unsigned long int statusData;
} CMCGReqFTfSt;


const unsigned long int MCGREQREQ2SENDF_FILENAME_SIZE = 256;
typedef struct {
	unsigned long int appVersion;
	unsigned long int transactionID;
	unsigned long int dataID;
	unsigned long int waysideRef;
	unsigned char filename[MCGREQREQ2SENDF_FILENAME_SIZE];
	unsigned long int filesize;
} CMCGReqReq2SendF;


const unsigned long int MCGREQREQFILE_FILENAME_SIZE = 256;
const unsigned long int MCGREQREQFILE_FILESERVERHOSTNAME_SIZE = 64;
const unsigned long int MCGREQREQFILE_FILESERVERPATH_SIZE = 256;
typedef struct {
	unsigned long int appVersion;
	unsigned long int transactionID;
	unsigned char filename[MCGREQREQFILE_FILENAME_SIZE];
	unsigned char fileServerHostname[MCGREQREQFILE_FILESERVERHOSTNAME_SIZE];
	unsigned char fileServerPath[MCGREQREQFILE_FILESERVERPATH_SIZE];
} CMCGReqReqFile;


const unsigned long int MCGREQSENDFILE_FILENAME_SIZE = 256;
const unsigned long int MCGREQSENDFILE_FILESERVERHOSTNAME_SIZE = 64;
const unsigned long int MCGREQSENDFILE_FILESERVERPATH_SIZE = 256;
const unsigned long int MCGREQSENDFILE_SPECIFICPARAMETERS_SIZE = 512;
typedef struct {
	unsigned long int appVersion;
	unsigned long int transactionID;
	unsigned char filename[MCGREQSENDFILE_FILENAME_SIZE];
	unsigned char fileServerHostname[MCGREQSENDFILE_FILESERVERHOSTNAME_SIZE];
	unsigned char fileServerPath[MCGREQSENDFILE_FILESERVERPATH_SIZE];
	unsigned long int filesize;
	unsigned long int fileCRC;
	unsigned long int fileVersion;
	unsigned short int noOfChars;
	unsigned char specificParameters[MCGREQSENDFILE_SPECIFICPARAMETERS_SIZE];
} CMCGReqSendFile;

#endif
