#ifndef SERP_ICD_H
#define SERP_ICD_H
/*
     This file is autogenerated.
     ICD_DB_VERSION 1.0.0.0
     DEVICE_INTERFACE_VERSION 0.0.19.0
     GDB_TOOL_VERSION 5.10.5

*/

 // ComID constants
#define COMID_OCCUC_DIS_I1 ((unsigned long int)240310100)
#define COMID_ICCUC_DIS_I1 ((unsigned long int)240310100)
#define COMID_OCCUC_INFDIS ((unsigned long int)272310100)
#define COMID_ICCUC_INFDIS ((unsigned long int)272310100)
#define COMID_OCCUOGLOBALA ((unsigned long int)201100100)
#define COMID_ICCUOGLOBALA ((unsigned long int)201100100)
#define COMID_IDISCTRLMAINT ((unsigned long int)240250100)
#define COMID_ODISCTRLMAINT ((unsigned long int)240250100)
#define COMID_ODISCTRLOP1 ((unsigned long int)240200100)
#define COMID_IDISCTRLOP1 ((unsigned long int)240200100)
#define COMID_IDISCTRLOP2 ((unsigned long int)240200200)
#define COMID_ODISCTRLOP2 ((unsigned long int)240200200)
#define COMID_IDIS1REPORT ((unsigned long int)240790100)
#define COMID_IDIS9REPORT ((unsigned long int)240790100)
#define COMID_IDIS11REPORT ((unsigned long int)240790100)
#define COMID_IDIS21REPORT ((unsigned long int)240790100)
#define COMID_IDIS12REPORT ((unsigned long int)240790100)
#define COMID_IDIS22REPORT ((unsigned long int)240790100)
#define COMID_IDIS13REPORT ((unsigned long int)240790100)
#define COMID_IDIS23REPORT ((unsigned long int)240790100)
#define COMID_IDIS14REPORT ((unsigned long int)240790100)
#define COMID_IDIS24REPORT ((unsigned long int)240790100)
#define COMID_IDIS15REPORT ((unsigned long int)240790100)
#define COMID_IDIS16REPORT ((unsigned long int)240790100)
#define COMID_IDIS26REPORT ((unsigned long int)240790100)
#define COMID_IDIS25REPORT ((unsigned long int)240790100)
#define COMID_IDIS17REPORT ((unsigned long int)240790100)
#define COMID_IDIS27REPORT ((unsigned long int)240790100)
#define COMID_IDIS18REPORT ((unsigned long int)240790100)
#define COMID_IDIS28REPORT ((unsigned long int)240790100)
#define COMID_IDIS19REPORT ((unsigned long int)240790100)
#define COMID_IDIS29REPORT ((unsigned long int)240790100)
#define COMID_IDISREPORT ((unsigned long int)240790100)
#define COMID_ODISREPORT ((unsigned long int)240790100)
#define COMID_OINFDISCTRLMAINT ((unsigned long int)272250100)
#define COMID_IINFDISCTRLMAINT ((unsigned long int)272250100)
#define COMID_OINFDISCTRLOP ((unsigned long int)272200100)
#define COMID_IINFDISCTRLOP ((unsigned long int)272200100)
#define COMID_OINFDISREPORT ((unsigned long int)272790100)
#define COMID_IINFDIS11REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS21REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS31REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS41REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS12REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS22REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS32REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS42REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS13REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS23REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS33REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS43REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS14REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS24REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS34REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS44REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS15REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS25REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS35REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS45REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS16REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS26REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS36REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS46REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS17REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS27REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS37REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS47REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS18REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS28REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS38REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS48REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS19REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS29REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS39REPORT ((unsigned long int)272790100)
#define COMID_IINFDIS49REPORT ((unsigned long int)272790100)
#define COMID_OPSCCOUNT ((unsigned long int)251600100)
#define COMID_IPSCCOUNT ((unsigned long int)251600100)
#define COMID_OPSCCTRLMAINT ((unsigned long int)251250100)
#define COMID_IPSCCTRLMAINT ((unsigned long int)251250100)
#define COMID_OPSCCTRLOP ((unsigned long int)251200100)
#define COMID_IPSCCTRLOP ((unsigned long int)251200100)
#define COMID_OPSCCTRLOP2 ((unsigned long int)251200200)
#define COMID_IPSCCTRLOP2 ((unsigned long int)251200200)
#define COMID_OPSCCTRLOP3 ((unsigned long int)251200300)
#define COMID_IPSCCTRLOP3 ((unsigned long int)251200300)
#define COMID_OPSCDIAG ((unsigned long int)251700100)
#define COMID_IPSCDIAG ((unsigned long int)251700100)
#define COMID_OPSCINTERN ((unsigned long int)251850100)
#define COMID_IPSCINTERN ((unsigned long int)251850100)
#define COMID_IPSCREPINTERN ((unsigned long int)251910100)
#define COMID_OPSCREPINTERN ((unsigned long int)251910100)
#define COMID_IPSCREQINTERN ((unsigned long int)251900100)
#define COMID_OPSCREQINTERN12 ((unsigned long int)251900100)
#define COMID_OPSCREQINTERN11 ((unsigned long int)251900100)
#define COMID_OPSCREQINTERN21 ((unsigned long int)251900100)
#define COMID_OPSCREQINTERN22 ((unsigned long int)251900100)
#define COMID_OPSCREQINTERN31 ((unsigned long int)251900100)
#define COMID_OPSCREQINTERN32 ((unsigned long int)251900100)
#define COMID_OPSCREQINTERN41 ((unsigned long int)251900100)
#define COMID_OPSCREQINTERN42 ((unsigned long int)251900100)
#define COMID_OPSCREQINTERN51 ((unsigned long int)251900100)
#define COMID_OPSCREQINTERN52 ((unsigned long int)251900100)
#define COMID_OPSCREQINTERN61 ((unsigned long int)251900100)
#define COMID_OPSCREQINTERN62 ((unsigned long int)251900100)
#define COMID_OPSCREQINTERN71 ((unsigned long int)251900100)
#define COMID_OPSCREQINTERN72 ((unsigned long int)251900100)
#define COMID_OPSCREQINTERN81 ((unsigned long int)251900100)
#define COMID_OPSCREQINTERN82 ((unsigned long int)251900100)
#define COMID_OPSCREQINTERN91 ((unsigned long int)251900100)
#define COMID_OPSCREQINTERN92 ((unsigned long int)251900100)
#define COMID_OPSCSTATUS ((unsigned long int)251500100)
#define COMID_IPSCSTATUS ((unsigned long int)251500100)


#define CCUC_DIS_I1_RESERVED1_SIZE ((unsigned long int)62)
//const unsigned long int CCUC_DIS_I1_RESERVED1_SIZE = 62;
typedef struct {
	unsigned short int IDisServLifeSign;
	unsigned char Reserved1[CCUC_DIS_I1_RESERVED1_SIZE];
} CCCUC_DIS_I1;


typedef struct {
	unsigned short int ICCUCLifeSign;
	unsigned short int Reserved1;
} CLifesign;


#define CCUC_INFDISLOADRESOURCE_RESERVED1_SIZE ((unsigned long int)3)
//const unsigned long int CCUC_INFDISLOADRESOURCE_RESERVED1_SIZE = 3;
typedef struct {
	unsigned char IInfdMode;
	unsigned char Reserved1[CCUC_INFDISLOADRESOURCE_RESERVED1_SIZE];
} CCCUC_INFDISLoadResource;

#define CCUC_INFDISLOADRESOURCE_IURL_SIZE ((unsigned long int)100)
#define CCUC_INFDISLOADRESOURCE_RESERVED2_SIZE ((unsigned long int)408)
//const unsigned long int CCUC_INFDISLOADRESOURCE_IURL_SIZE = 100;
//const unsigned long int CCUC_INFDISLOADRESOURCE_RESERVED1_SIZE = 408;
typedef struct {
	unsigned char IURL[CCUC_INFDISLOADRESOURCE_IURL_SIZE];
	unsigned char Reserved1[CCUC_INFDISLOADRESOURCE_RESERVED2_SIZE];
} CCCUC_INFDISLoadResource2;


typedef struct {
	CLifesign Lifesign;
	CCCUC_INFDISLoadResource LoadResource;
	CCCUC_INFDISLoadResource2 LoadResource2;
} CCCUC_INFDIS;

#define LIFESIGNCCUO_RESERVED1_SIZE ((unsigned long int)2)
//const unsigned long int LIFESIGNCCUO_RESERVED1_SIZE = 2;
typedef struct {
	unsigned short int ICcuLifeSign;
	unsigned char Reserved1[LIFESIGNCCUO_RESERVED1_SIZE];
} CLifeSignCCUO;

#define SPEED_RESERVED1_SIZE ((unsigned long int)2)
//const unsigned long int SPEED_RESERVED1_SIZE = 2;
typedef struct {
	unsigned short int ITrainSpeed;
	unsigned char Reserved1[SPEED_RESERVED1_SIZE];
} CSpeed;

#define UTCTIME_RESERVED2_SIZE ((unsigned long int)2)
//const unsigned long int UTCTIME_RESERVED2_SIZE = 2;
typedef struct {
	unsigned long int ISystemUtcTime;
	unsigned long int Reserved1;
	unsigned char IDaylightTime;
	unsigned char ITimeZone;
	unsigned char Reserved2[UTCTIME_RESERVED2_SIZE];
} CUtcTime;


typedef struct {
	unsigned short int IProjectID;
	unsigned char IProjectVariant;
	unsigned char Reserved1;
} CTrainConfiguration;

#define TRAINMODE_RESERVED1_SIZE ((unsigned long int)3)
//const unsigned long int TRAINMODE_RESERVED1_SIZE = 3;
typedef struct {
	unsigned char ITrainMode;
	unsigned char Reserved1[TRAINMODE_RESERVED1_SIZE];
} CTrainMode;

#define SWDOWNLDMODE_RESERVED1_SIZE ((unsigned long int)8)
#define SWDOWNLDMODE_RESERVED2_SIZE ((unsigned long int)3)
//const unsigned long int SWDOWNLDMODE_RESERVED1_SIZE = 8;
//onst unsigned long int SWDOWNLDMODE_RESERVED2_SIZE = 3;
typedef struct {
	unsigned char IRemSwDownLdMode;
	unsigned char Reserved1[SWDOWNLDMODE_RESERVED1_SIZE];
	unsigned char Reserved2[SWDOWNLDMODE_RESERVED2_SIZE];
} CSWDownLdMode;

#define AUXILIARYPOWER_RESERVED3_SIZE ((unsigned long int)2)
//const unsigned long int AUXILIARYPOWER_RESERVED3_SIZE = 2;
typedef struct {
	unsigned char Reserved1;
	unsigned char Reserved2;
	unsigned char Reserved3[AUXILIARYPOWER_RESERVED3_SIZE];
} CAuxiliaryPower;

#define TEMPERATURE_RESERVED1_SIZE ((unsigned long int)2)
//const unsigned long int TEMPERATURE_RESERVED1_SIZE = 2;
typedef struct {
	short int ITempOutside;
	unsigned char Reserved1[TEMPERATURE_RESERVED1_SIZE];
} CTemperature;

#define STANDARDFIELD_IMISSIONCODE_SIZE ((unsigned long int)4)
#define STANDARDFIELD_ICONTAINER1_SIZE ((unsigned long int)112)
#define STANDARDFIELD_RESERVED1_SIZE ((unsigned long int)4)
//const unsigned long int STANDARDFIELD_IMISSIONCODE_SIZE = 4;
//const unsigned long int STANDARDFIELD_ICONTAINER1_SIZE = 112;
//const unsigned long int STANDARDFIELD_RESERVED1_SIZE = 4;
typedef struct {
	unsigned char IMissionCode[STANDARDFIELD_IMISSIONCODE_SIZE];
	unsigned char IContainer1[STANDARDFIELD_ICONTAINER1_SIZE];
	unsigned char Reserved1[STANDARDFIELD_RESERVED1_SIZE];
} CStandardField;

#define PROJECTFIELD_ILINEPLATFORMID_SIZE ((unsigned long int)8)
#define PROJECTFIELD_IPREVSTATIONID_SIZE ((unsigned long int)8)
#define PROJECTFIELD_INEXTSTATIONID_SIZE ((unsigned long int)8)
#define PROJECTFIELD_IDESTSTATIONID_SIZE ((unsigned long int)8)
#define PROJECTFIELD_ICONTAINER2_SIZE ((unsigned long int)85)
//const unsigned long int PROJECTFIELD_ILINEPLATFORMID_SIZE = 8;
//const unsigned long int PROJECTFIELD_IPREVSTATIONID_SIZE = 8;
//const unsigned long int PROJECTFIELD_INEXTSTATIONID_SIZE = 8;
//const unsigned long int PROJECTFIELD_IDESTSTATIONID_SIZE = 8;
//const unsigned long int PROJECTFIELD_ICONTAINER2_SIZE = 85;
typedef struct {
	float IHeading;
	float ILongtitude;
	float ILatitude;
	float IAltitude;
	unsigned long int IDistanceTravelled;
	unsigned char ITrainSpeedStatus;
	unsigned char ITrainLocation;
	unsigned char ILineDir;
	unsigned char IGPSRxrOffset;
	unsigned char IGPSPositionFix;
	unsigned char IDoorReleaseStatus;
	unsigned char ILinePlatformID[PROJECTFIELD_ILINEPLATFORMID_SIZE];
	unsigned char IPrevStationID[PROJECTFIELD_IPREVSTATIONID_SIZE];
	unsigned char INextStationID[PROJECTFIELD_INEXTSTATIONID_SIZE];
	unsigned char IDestStationID[PROJECTFIELD_IDESTSTATIONID_SIZE];
	unsigned char IContainer2[PROJECTFIELD_ICONTAINER2_SIZE];
	unsigned char Reserved1;
} CProjectField;


typedef struct {
	unsigned char IDrivDeskxOccup;
	unsigned char IDrivDesk1Occup;
	unsigned char IDrivDesk2Occup;
	unsigned char Reserved1;
} CDriverDesk;

#define TUNNELSTATUS_RESERVED1_SIZE ((unsigned long int)3)
//const unsigned long int TUNNELSTATUS_RESERVED1_SIZE = 3;
typedef struct {
	unsigned char ITunnelPosition;
	unsigned char Reserved1[TUNNELSTATUS_RESERVED1_SIZE];
} CTunnelStatus;


typedef struct {
	CLifeSignCCUO LifeSignCCUO;
	CSpeed Speed;
	CUtcTime UtcTime;
	CTrainConfiguration TrainConfiguration;
	CTrainMode TrainMode;
	CSWDownLdMode SWDownLdMode;
	CAuxiliaryPower AuxiliaryPower;
	CTemperature Temperature;
	CStandardField StandardField;
	CProjectField ProjectField;
	CDriverDesk DriverDesk;
	CTunnelStatus TunnelStatus;
} CCCUOGlobalA;

#define DISCTRLMAINT_RESERVED1_SIZE ((unsigned long int)126)
//const unsigned long int DISCTRLMAINT_RESERVED1_SIZE = 126;
typedef struct {
	unsigned char CReset;
	unsigned char CResetFaultLog;
	unsigned char Reserved1[DISCTRLMAINT_RESERVED1_SIZE];
} CDISCtrlMaint;

#define DISCTRLOP1_RESERVED2_SIZE ((unsigned long int)15)
#define DISCTRLOP1_RESERVED3_SIZE ((unsigned long int)47)
//const unsigned long int DISCTRLOP1_RESERVED2_SIZE = 15;
//const unsigned long int DISCTRLOP1_RESERVED3_SIZE = 47;
typedef struct {
	unsigned char Reserved1;
	unsigned char CBufferCopy;
	unsigned char Reserved2[DISCTRLOP1_RESERVED2_SIZE];
	unsigned char CSystemMode;
	unsigned char Reserved3[DISCTRLOP1_RESERVED3_SIZE];
} CDISCtrlOp1;

#define DISCTRLOP2_CMESSAGE_SIZE ((unsigned long int)1000)
#define DISCTRLOP2_RESERVED1_SIZE ((unsigned long int)20)
//const unsigned long int DISCTRLOP2_CMESSAGE_SIZE = 1000;
//const unsigned long int DISCTRLOP2_RESERVED1_SIZE = 20;
typedef struct {
	unsigned char CEndMessage;
	unsigned char CSubMessageNb;
	unsigned short int CMessageLength;
	unsigned char CMessage[DISCTRLOP2_CMESSAGE_SIZE];
	unsigned char Reserved1[DISCTRLOP2_RESERVED1_SIZE];
} CDISCtrlOp2;

#define DISREPORTSTATUSDATA_RESERVED1_SIZE ((unsigned long int)121)
//const unsigned long int DISREPORTSTATUSDATA_RESERVED1_SIZE = 121;
typedef struct {
	unsigned short int ISystemLifeSign;
	unsigned char ISystemMode;
	unsigned char ITestMode;
	unsigned char ITreatBufferF1;
	unsigned char ITreatBufferF2;
	unsigned char ITreatBufferF3;
	unsigned char Reserved1[DISREPORTSTATUSDATA_RESERVED1_SIZE];
} CDISReportStatusData;

#define DISREPORTCNTDATA_RESERVED1_SIZE ((unsigned long int)52)
//const unsigned long int DISREPORTCNTDATA_RESERVED1_SIZE = 52;
typedef struct {
	unsigned long int IDISWorkTime;
	unsigned long int IDISPowerUp;
	unsigned long int IDISWatchdog;
	unsigned char Reserved1[DISREPORTCNTDATA_RESERVED1_SIZE];
} CDISReportCntData;

#define DISREPORTDIAGDATACOMMODULE_RESERVED2_SIZE ((unsigned long int)2)
//const unsigned long int DISREPORTDIAGDATACOMMODULE_RESERVED2_SIZE = 2;
typedef struct {
	unsigned char Reserved1;
	unsigned char FTimeoutComMod;
	unsigned char Reserved2[DISREPORTDIAGDATACOMMODULE_RESERVED2_SIZE];
} CDISReportDiagDataCOMModule;

#define DISREPORTDIAGDATAAPPLICATIONMODULE_RESERVED1_SIZE ((unsigned long int)2)
//const unsigned long int DISREPORTDIAGDATAAPPLICATIONMODULE_RESERVED1_SIZE = 2;
typedef struct {
	unsigned char FWatchdogApiMod;
	unsigned char FApiMod;
	unsigned char Reserved1[DISREPORTDIAGDATAAPPLICATIONMODULE_RESERVED1_SIZE];
} CDISReportDiagDataApplicationModule;

#define DISPLAYFAULTS_RESERVED2_SIZE ((unsigned long int)42)
//const unsigned long int DISPLAYFAULTS_RESERVED2_SIZE = 42;
typedef struct {
	unsigned char FTempExceeded;
	unsigned char FAmbLightSensor;
	unsigned char FTempHigh;
	unsigned char FTempSensor;
	unsigned char Reserved1;
	unsigned char FLEDBoardFault;
	unsigned char Reserved2[DISPLAYFAULTS_RESERVED2_SIZE];
} CDisplayFaults;


typedef struct {
	CDISReportDiagDataCOMModule COMModule;
	CDISReportDiagDataApplicationModule ApplicationModule;
	CDisplayFaults DisplayFaults;
} CDISReportDiagData;


typedef struct {
	CDISReportStatusData StatusData;
	CDISReportCntData CntData;
	CDISReportDiagData DiagData;
} CDISReport;

#define COMMANDS_RESERVED2_SIZE ((unsigned long int)16)
//const unsigned long int COMMANDS_RESERVED2_SIZE = 16;
typedef struct {
	unsigned char CReset;
	unsigned char Reserved1;
	unsigned char Reserved2[COMMANDS_RESERVED2_SIZE];
} CCommands;

#define INFDCOUNTERCOMMANDS_RESERVED1_SIZE ((unsigned long int)41)
//const unsigned long int INFDCOUNTERCOMMANDS_RESERVED1_SIZE = 41;
typedef struct {
	unsigned char CDurationCounterReset;
	unsigned char CBackOnCounterReset;
	unsigned char CNormalStartsCounterReset;
	unsigned char CWdogResetsCounterReset;
	unsigned char CResetAllCounters;
	unsigned char Reserved1[INFDCOUNTERCOMMANDS_RESERVED1_SIZE];
} CINFDCounterCommands;

#define RUNTIMEPARAMETEROVERWRITE_RESERVED1_SIZE ((unsigned long int)18)
#define RUNTIMEPARAMETEROVERWRITE_RESERVED2_SIZE ((unsigned long int)46)
//const unsigned long int RUNTIMEPARAMETEROVERWRITE_RESERVED1_SIZE = 18;
//const unsigned long int RUNTIMEPARAMETEROVERWRITE_RESERVED2_SIZE = 46;
typedef struct {
	unsigned char Reserved1[RUNTIMEPARAMETEROVERWRITE_RESERVED1_SIZE];
	unsigned char Reserved2[RUNTIMEPARAMETEROVERWRITE_RESERVED2_SIZE];
} CRuntimeParameterOverwrite;


typedef struct {
	CCommands Commands;
	CINFDCounterCommands INFDCounterCommands;
	CRuntimeParameterOverwrite RuntimeParameterOverwrite;
} CINFDISCtrlMaint;

#define CTRLCOMMANDS_RESERVED1_SIZE ((unsigned long int)2)
#define CTRLCOMMANDS_RESERVED2_SIZE ((unsigned long int)13)
#define CTRLCOMMANDS_RESERVED3_SIZE ((unsigned long int)46)
//const unsigned long int CTRLCOMMANDS_RESERVED1_SIZE = 2;
//const unsigned long int CTRLCOMMANDS_RESERVED2_SIZE = 13;
//const unsigned long int CTRLCOMMANDS_RESERVED3_SIZE = 46;
typedef struct {
	unsigned char CShutdownCmd;
	unsigned char CBacklightCmd;
	unsigned char Reserved1[CTRLCOMMANDS_RESERVED1_SIZE];
	unsigned char Reserved2[CTRLCOMMANDS_RESERVED2_SIZE];
	unsigned char CSystemMode;
	unsigned char Reserved3[CTRLCOMMANDS_RESERVED3_SIZE];
} CCtrlCommands;


typedef struct {
	CCtrlCommands CtrlCommands;
} CINFDISCtrlOp;

#define INFDISREPORTSTATUSDATA_RESERVED1_SIZE ((unsigned long int)61)
//const unsigned long int INFDISREPORTSTATUSDATA_RESERVED1_SIZE = 61;
typedef struct {
	unsigned short int ISystemLifeSign;
	unsigned char ISystemMode;
	unsigned char ITestMode;
	unsigned char IBacklightStatus;
	unsigned char Reserved1[INFDISREPORTSTATUSDATA_RESERVED1_SIZE];
} CINFDISReportStatusData;

#define INFDISREPORTCNTDATA_RESERVED1_SIZE ((unsigned long int)48)
//const unsigned long int INFDISREPORTCNTDATA_RESERVED1_SIZE = 48;
typedef struct {
	unsigned long int ITFTWorkTime;
	unsigned long int ITFTBacklight;
	unsigned long int ITFTPowerUp;
	unsigned long int ITFTWatchdog;
	unsigned char Reserved1[INFDISREPORTCNTDATA_RESERVED1_SIZE];
} CINFDISReportCntData;

#define INFDISREPORTDIAGDATACOMMODULE_RESERVED2_SIZE ((unsigned long int)4)
//const unsigned long int INFDISREPORTDIAGDATACOMMODULE_RESERVED2_SIZE = 4;
typedef struct {
	unsigned char Reserved1;
	unsigned char FTimeoutComMod;
	unsigned char Reserved2[INFDISREPORTDIAGDATACOMMODULE_RESERVED2_SIZE];
} CINFDISReportDiagDataCOMModule;

#define INFDISREPORTDIAGDATAAPPLICATIONMODULE_RESERVED1_SIZE ((unsigned long int)2)
//const unsigned long int INFDISREPORTDIAGDATAAPPLICATIONMODULE_RESERVED1_SIZE = 2;
typedef struct {
	unsigned char FWatchdogApiMod;
	unsigned char FApiMod;
	unsigned char Reserved1[INFDISREPORTDIAGDATAAPPLICATIONMODULE_RESERVED1_SIZE];
} CINFDISReportDiagDataApplicationModule;

#define TFTFAULTS_RESERVED2_SIZE ((unsigned long int)44)
//const unsigned long int TFTFAULTS_RESERVED2_SIZE = 44;
typedef struct {
	unsigned char FBcklightFault;
	unsigned char FTempSensor;
	unsigned char FTempORHigh;
	unsigned char FTempORLow;
	unsigned char Reserved1;
	unsigned char FAmbLightSensor;
	unsigned char Reserved2[TFTFAULTS_RESERVED2_SIZE];
} CTFTFaults;


typedef struct {
	CINFDISReportDiagDataCOMModule COMModule;
	CINFDISReportDiagDataApplicationModule ApplicationModule;
	CTFTFaults TFTFaults;
} CINFDISReportDiagData;


typedef struct {
	CINFDISReportStatusData StatusData;
	CINFDISReportCntData CntData;
	CINFDISReportDiagData DiagData;
} CINFDISReport;

#define PSCCOUNT_RESERVED1_SIZE ((unsigned long int)52)
//const unsigned long int PSCCOUNT_RESERVED1_SIZE = 52;
typedef struct {
	unsigned long int IPscWorkTime;
	unsigned long int IPscPowerUp;
	unsigned long int IPscWatchdog;
	unsigned char Reserved1[PSCCOUNT_RESERVED1_SIZE];
} CPSCCount;

#define PSCCTRLMAINT_RESERVED1_SIZE ((unsigned long int)62)
//const unsigned long int PSCCTRLMAINT_RESERVED1_SIZE = 62;
typedef struct {
	unsigned char CResetSystem;
	unsigned char CResetFaultLog;
	unsigned char Reserved1[PSCCTRLMAINT_RESERVED1_SIZE];
} CPSCCtrlMaint;

#define INSTRUCTIONS_CPRMMESSAGE_SIZE ((unsigned long int)4000)
#define INSTRUCTIONS_RESERVED1_SIZE ((unsigned long int)91)
//const unsigned long int INSTRUCTIONS_CPRMMESSAGE_SIZE = 4000;
//const unsigned long int INSTRUCTIONS_RESERVED1_SIZE = 91;
typedef struct {
	unsigned long int CMessageLength;
	unsigned char CPrmMessage[INSTRUCTIONS_CPRMMESSAGE_SIZE];
	unsigned char Reserved1[INSTRUCTIONS_RESERVED1_SIZE];
} CInstructions;

#define PSCCTRLOP_RESERVED1_SIZE ((unsigned long int)2)
//const unsigned long int PSCCTRLOP_RESERVED1_SIZE = 2;
typedef struct {
	unsigned char Reserved1[PSCCTRLOP_RESERVED1_SIZE];
	CInstructions Instructions;
} CPSCCtrlOp;


typedef struct {
	unsigned char CSelectActivePCUCd;
	unsigned char CSelectActivePCUVal;
	unsigned char Reserved1;
} CPCUSelection;

#define CABAUDIOMUTE_RESERVED1_SIZE ((unsigned long int)9)
//const unsigned long int CABAUDIOMUTE_RESERVED1_SIZE = 9;
typedef struct {
	unsigned char CPISCabAudioMute;
	unsigned char Reserved1[CABAUDIOMUTE_RESERVED1_SIZE];
} CCabAudioMute;


typedef struct {
	unsigned char CConsistNumber;
	unsigned char Reserved1;
	CPCUSelection PCUSelection;
	CCabAudioMute CabAudioMute;
} CPSCCtrlOp2;

#define PSCCTRLOP3_RESERVED3_SIZE ((unsigned long int)10)
//const unsigned long int PSCCTRLOP3_RESERVED3_SIZE = 10;
typedef struct {
	unsigned char CSystemMode;
	unsigned char Reserved1;
	unsigned char CResetPCU;
	unsigned char Reserved2;
	unsigned char CSaloonAlarm;
	unsigned char Reserved3[PSCCTRLOP3_RESERVED3_SIZE];
} CPSCCtrlOp3;

#define PSCDIAG_RESERVED1_SIZE ((unsigned long int)4)
#define PSCDIAG_RESERVED2_SIZE ((unsigned long int)3)
//const unsigned long int PSCDIAG_RESERVED1_SIZE = 4;
//const unsigned long int PSCDIAG_RESERVED2_SIZE = 3;
typedef struct {
	unsigned char FTimeoutComMod;
	unsigned char FPscRedunSysAct;
	unsigned char FPsc1ErrorStatus;
	unsigned char FPsc2ErrorStatus;
	unsigned char Reserved1[PSCDIAG_RESERVED1_SIZE];
	unsigned char FPscTrainErrorStatus;
	unsigned char Reserved2[PSCDIAG_RESERVED2_SIZE];
} CPSCDiag;

#define PSCPERIPHDIAG_FPCUERRORSTATUS_SIZE ((unsigned long int)128)
#define PSCPERIPHDIAG_FPIUERRORSTATUS_SIZE ((unsigned long int)5)
#define PSCPERIPHDIAG_RESERVED1_SIZE ((unsigned long int)51)
//const unsigned long int PSCPERIPHDIAG_FPCUERRORSTATUS_SIZE = 128;
//const unsigned long int PSCPERIPHDIAG_FPIUERRORSTATUS_SIZE = 5;
//const unsigned long int PSCPERIPHDIAG_RESERVED1_SIZE = 51;
typedef struct {
	unsigned short int FPcuErrorStatus[PSCPERIPHDIAG_FPCUERRORSTATUS_SIZE];
	unsigned char FPiuErrorStatus[PSCPERIPHDIAG_FPIUERRORSTATUS_SIZE];
	unsigned char Reserved1[PSCPERIPHDIAG_RESERVED1_SIZE];
} CPSCPeriphDiag;


typedef struct {
	CPSCDiag PSCDiag;
	CPSCPeriphDiag PSCPeriphDiag;
} CPSCDiagTot;


typedef struct {
	unsigned char Reserved1;
} CPSCIntern;


typedef struct {
	unsigned char Reserved1;
} CPSCRepIntern;


typedef struct {
	unsigned char Reserved1;
} CPSCReqIntern;

#define PSCSTATUS_RESERVED2_SIZE ((unsigned long int)10)
//const unsigned long int PSCSTATUS_RESERVED2_SIZE = 10;
typedef struct {
	unsigned short int ISystemLifeSign;
	unsigned char ISystemMode;
	unsigned char ITestMode;
	unsigned char IPrmFuncSt;
	unsigned char IIntercomFuncSt;
	unsigned char IPublicAddFuncSt;
	unsigned char IPassComFuncSt;
	unsigned char ISystModeForced;
	unsigned char Reserved1;
	unsigned short int IRedMode;
	unsigned short int IPRAMode;
	unsigned short int ICab1AudioMute;
	unsigned short int ICab2AudioMute;
	unsigned char Reserved2[PSCSTATUS_RESERVED2_SIZE];
} CPSCStatus;

#define PSCPERIPHSTATUS_IPCUPANELSTAT_SIZE ((unsigned long int)128)
#define PSCPERIPHSTATUS_IPIUSTATUS_SIZE ((unsigned long int)5)
#define PSCPERIPHSTATUS_RESERVED1_SIZE ((unsigned long int)11)
//const unsigned long int PSCPERIPHSTATUS_IPCUPANELSTAT_SIZE = 128;
//const unsigned long int PSCPERIPHSTATUS_IPIUSTATUS_SIZE = 5;
//const unsigned long int PSCPERIPHSTATUS_RESERVED1_SIZE = 11;
typedef struct {
	unsigned char IPcuPanelStat[PSCPERIPHSTATUS_IPCUPANELSTAT_SIZE];
	unsigned char IPiuStatus[PSCPERIPHSTATUS_IPIUSTATUS_SIZE];
	unsigned char Reserved1[PSCPERIPHSTATUS_RESERVED1_SIZE];
} CPSCPeriphStatus;


typedef struct {
	CPSCStatus PSCStatus;
	CPSCPeriphStatus PSCPeriphStatus;
} CPSCStatusTot;

#endif
