#!/bin/sh
MULTICAST_IP_ADDR="239.255.12.42"
VIDEO_UDP_PORT=5004
WIDTH=960
HEIGHT=380
TOP=0
LEFT=0


gst-launch-0.10 udpsrc multicast-group=${MULTICAST_IP_ADDR} auto-multicast=true port=${VIDEO_UDP_PORT} \
caps = 'application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, sprop-parameter-sets=(string)\"Z01AKOygPAET8uAtQEBAUAAAAwAQAAADA8jxgxlg\\,aO+G8g\\=\\=\", payload=(int)96, ssrc=(uint)2865005897, clock-base=(uint)2796149566, seqnum-base=(uint)62836' \
! rtph264depay ! vpudec ! mfw_v4lsink sync=false disp-width=${WIDTH} disp-height=${HEIGHT} axis-top=${TOP} axis-left=${LEFT}

